# Generated by Django 5.0.4 on 2024-07-24 18:08

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_remove_playerstatistics_longest_growth_cycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), size=None)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.studentprofile')),
            ],
        ),
    ]
