# Generated by Django 5.0.4 on 2024-07-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatistics',
            name='coins_collected',
            field=models.PositiveIntegerField(default=0, help_text='Монет заработано'),
        ),
    ]
