# Generated by Django 5.0.4 on 2024-07-25 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_playerstatistics_coins_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=300), help_text='Длительность негативного ивента'),
        ),
        migrations.AddField(
            model_name='tree',
            name='event',
            field=models.PositiveIntegerField(choices=[(0, 'UFO'), (1, 'Drought'), (2, 'Flood')], help_text='Следующий катаклизм', null=True),
        ),
        migrations.AddField(
            model_name='tree',
            name='start_time',
            field=models.DateTimeField(help_text='Время начала негативного ивента', null=True),
        ),
        migrations.AlterField(
            model_name='counterofbusters',
            name='count',
            field=models.PositiveIntegerField(default=0, help_text='Количество бустеров у студента'),
        ),
    ]
