# Generated by Django 5.0.4 on 2024-08-06 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_alter_attendance_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ('last_name', 'first_name')},
        ),
    ]
