# Generated by Django 5.0.4 on 2024-08-16 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_alter_studentprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='statistics',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.playerstatistics'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='stage',
            field=models.PositiveIntegerField(choices=[(1, 'FIRST STAGE'), (2, 'SECOND STAGE'), (3, 'THIRD STAGE'), (4, 'MONEY COLLECT STAGE')], default=0, help_text='Стадия роста дерева'),
        ),
    ]
