# Generated by Django 5.0.4 on 2024-08-16 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_alter_studentprofile_statistics_alter_tree_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='statistics',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.playerstatistics'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='tree',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.tree'),
        ),
    ]
