# Generated by Django 5.0.4 on 2024-08-18 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_alter_studentprofile_statistics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=300), help_text='Длительность негативного ивента', null=True),
        ),
    ]
