# Generated by Django 5.0.4 on 2024-08-18 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_alter_tree_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=300), help_text='Длительность негативного ивента'),
        ),
    ]
