# Generated by Django 5.0.4 on 2024-08-19 14:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_alter_tree_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='treestatistics',
            name='drought_repulsed',
            field=models.PositiveIntegerField(default=0, help_text='Засух отбито'),
        ),
        migrations.AddField(
            model_name='treestatistics',
            name='flood_repulsed',
            field=models.PositiveIntegerField(default=0, help_text='Наводнений отбито'),
        ),
        migrations.AddField(
            model_name='treestatistics',
            name='ufo_repulsed',
            field=models.PositiveIntegerField(default=0, help_text='Нло отбито'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=300), help_text='Длительность негативного ивента'),
        ),
        migrations.AlterField(
            model_name='treestatistics',
            name='coins_collected',
            field=models.PositiveIntegerField(default=0, help_text='Монет заработано c этого дерева'),
        ),
        migrations.AlterField(
            model_name='treestatistics',
            name='tree',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='user_profile.tree'),
        ),
    ]
