# Generated by Django 5.1.1 on 2024-09-18 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_schoolname_alter_user_is_staff_admincode_and_more'),
        ('user_profile', '0014_mentorprofile_code_personalprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.schoolname'),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.schoolname'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.schoolname'),
        ),
    ]
