# Generated by Django 5.0.4 on 2024-07-24 17:51

from django.db import migrations


def init_busters(apps, shema_editor):
    Buster = apps.get_model('shop', 'Buster')

    Buster.objects.bulk_create([
        Buster(
            title='Магический купол',
            description='спасает от наводнения',
            cost='30',
            picture='/busters/Magicdom.png'
        ),
        Buster(
            title='Ведро с водой',
            description='помогает при засухе',
            cost='30',
            picture='/busters/Waterbucket.png'
        ),
        Buster(
            title='Антимагнит',
            description='помогает при нападении инопланетян',
            cost='30',
            picture='/busters/Antimagnet.png'
        )
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_busters)
    ]
