# Generated by Django 5.0.4 on 2024-10-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('requirement', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('pic', models.ImageField(blank=True, default='default_pics/achievment.png', help_text='Фото ачивки', null=True, upload_to='achievements/')),
                ('reward', models.PositiveIntegerField()),
            ],
        ),
    ]
