# Generated by Django 5.0.4 on 2024-07-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='pic',
            field=models.ImageField(blank=True, default='media/default_pics/achievment.png', help_text='Фото ачивки', null=True, upload_to='achievements/'),
        ),
    ]
