# Generated by Django 5.0.4 on 2024-07-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievments', '0002_alter_achievements_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='pic',
            field=models.ImageField(blank=True, default='123/default_pics/achievment.png', help_text='Фото ачивки', null=True, upload_to='achievements/'),
        ),
    ]
