# Generated by Django 5.0.4 on 2024-07-24 17:53

from django.db import migrations


def init_achievements(apps, shema_editor):
    Achievements = apps.get_model('achievments', 'Achievements')

    Achievements.objects.bulk_create([
        Achievements(title='Зеленый росток',
                     description='Ты только начал, но уже защищаешь свое дерево как настоящий садовник!',
                     requirement='Защити дерево от 5 атак',
                     reward=1),
        Achievements(title='Солнечный луч',
                     description='Первые монеты собраны! Продолжай в том же духе!',
                     requirement='Собери 10 монет с дерева',
                     reward=1),
        Achievements(title='Против наводнения',
                     description='Ты смог спасти дерево от наводнения!',
                     requirement='Отбей 2 атаки дождя',
                     reward=1),
        Achievements(title='Ночной дозор',
                     description='НЛО не смогло похитить твое дерево благодаря твоей защите!',
                     requirement='Защити дерево от атаки НЛО',
                     reward=1),
        Achievements(title='Стойкий оловянный солдатик',
                     description='Ты настоящий защитник своего дерева!',
                     requirement='Защити дерево от 20 атак',
                     reward=3),
        Achievements(title='Денежное дерево',
                     description='Твое дерево приносит всё больше монет!',
                     requirement='Собери 50 монет с дерева',
                     reward=2),
        Achievements(title='Не тронь моё дерево!',
                     description='Никто не может повредить твое дерево!',
                     requirement='Отбей 10 атак всех видов "врагов"',
                     reward=2),
        Achievements(title='Лесной гигант',
                     description='Твое дерево стало настоящим гигантом!',
                     requirement='Собери 200 монет с дерева',
                     reward=3),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('achievments', '0005_alter_achievements_pic'),
    ]

    operations = [
        migrations.RunPython(init_achievements)
    ]
